language: python
python: "3.5"

before_install:
  - cd /tmp/ && curl -O https://gandra.fim.uni-passau.de/~tux/win10.zip && unzip win10.zip && rm win10.zip
  - echo "Sum should be 34c42d4c35cd7df1a94ecb6bdd568a90"
  - md5sum /tmp/win10.raw
  - pip3 install pefile 
    #  - pip2 install distorm3
  - pip2 install --user pycrypto distorm3
  
  
install:
  - git clone https://github.com/volatilityfoundation/volatility.git /tmp/volatility
  - git clone https://github.com/volatilityfoundation/volatility3.git /tmp/vol3
  - cd /tmp/vol3/volatility/symbols && wget https://downloads.volatilityfoundation.org/volatility3/symbols/windows.zip && unzip windows.zip > /dev/null

script:
  - bash -c "echo \"{ 'primary.class': 'volatility.framework.layers.intel.WindowsIntel32e', 'primary.page_map_offset': 1744896 }\" > /tmp/vol3/conf.json "
  - cd /tmp/vol3 && python3 vol.py -vvv --config conf.json -f /tmp/win10.raw windows.pslist
  - cd /tmp/vol3 && python3 vol.py -vvv --config conf.json -f /tmp/win10.raw windows.info
  - cd /tmp/vol3 && python3 vol.py -vvv --config conf.json -f /tmp/win10.raw windows.verinfo.VerInfo
