language: python
python: "2.7"

before_install:
  - git clone https://github.com/volatilityfoundation/volatility.git /tmp/volatility
  - curl -O https://storage.googleapis.com/volatility-autoruns/BOBBY-PC.raw.gz
  - gunzip BOBBY-PC.raw.gz

install:
  - pip install pycrypto
  - pip install /tmp/volatility

script:
  - vol.py --plugins=. -f BOBBY-PC.raw --profile=Win7SP1x64 autoruns --output-file=output.json --output=json -v
  - jq . output.json > output_pretty.json
  - diff output_pretty.json test_data/expected_output_pretty.json
